In [1]:
import numpy as np

In [2]:
my_array = np.arange(0,11)

In [3]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
my_array[:5]

# start(0) se leke 5 tak

array([0, 1, 2, 3, 4])

In [7]:
# BROADCASTING

my_array[9:] = 69

# we are reassigning the values mentioned in the range 9:end_tak to 69, we cannot do this in normal

In [8]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 69, 69])

In [15]:
sliced_array = my_array[:3] 

# slicing the original array into a smaller array for something i wanna show later
# PS: IT IS JUST A POINTER TO THE ORIGINAL ARRAY

# IF YOU CHANGE THE SLICED ARRAY (a pointer to og) IT WILL CHANGE THE OG ARRAY

In [10]:
sliced_array

array([0, 1, 2])

In [12]:
sliced_array[:] = 420 

# broadcasting all the values of the sliced array

In [13]:
sliced_array

array([420, 420, 420])

In [14]:
# WILL IT HAVE ANY CHANGE ON THE ORIGINAL ARRAY ?

my_array

# YES.

array([420, 420, 420,   3,   4,   5,   6,   7,   8,  69,  69])

In [16]:
new_array = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [17]:
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
new_array.shape

(3, 3)

In [21]:
new_array[0,1]

# is the same as new_array[0][1]

2

In [24]:
# trying out slice with 2d indexing

new_sliced_array = new_array[:2, 1:] 

# not used very often tho

In [25]:
new_sliced_array

array([[2, 3],
       [5, 6]])

In [26]:
# SELECTION

In [36]:
one_array = np.arange(0,11)

In [37]:
one_array > 3

# returns a boolean array suggesting true or false for the given condition

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [38]:
bool_array = one_array > 3

In [39]:
one_array[bool_array]

# THIS WILL GIVE ONLY TRUE VALUED ARGUMENTS

array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
# FOR SHORT WE CAN DO, VERY IMPORTANT

one_array[one_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])